"use strict";
exports.__esModule = true;
var ITEM_WITH_RESOLVED_DATA_FIELDS;
(function (ITEM_WITH_RESOLVED_DATA_FIELDS) {
    ITEM_WITH_RESOLVED_DATA_FIELDS["CATEGORY"] = "category";
    ITEM_WITH_RESOLVED_DATA_FIELDS["RESOLVED_DATA"] = "resolvedData";
})(ITEM_WITH_RESOLVED_DATA_FIELDS || (ITEM_WITH_RESOLVED_DATA_FIELDS = {}));
exports["default"] = ITEM_WITH_RESOLVED_DATA_FIELDS;
